### ISSUE TITLE
Doesn't work with Sequilize@5.1.0

### ISSUE THREAD

**Issue by FY0u11** [natesilva/koa-generic-session-sequelize#2]
Hello. Please change the method of Sequelize in index.js on 102th line. 
`return this.Model.findOrInitialize({ where: { id: sid } })` 
to 
`return this.Model.findOrBuild({ where: { id: sid } })`
because koa-generic-session-sequelize doesn't work without this fix on Sequelize@5.1.0

**Comment by natesilva** [comment]
This is now fixed in the latest version 2.2.0.
